secret:
    databaseUrl: ENC[AES256_GCM,data:upS+Ms6cKw579HJSR2eZNZHCrxt0wtXXTCgXm3OIZLoWf3NEmSAgWKqF1ROfysJOQGXoQ/rd1s3k0lNlBinmVZOUOWULyCrzEBJ6Zp4hOG5k4U5H10YfajG7WrLpvzpRe6XEhYfI,iv:PoT8VlncCtuvrVikkYEcy6VEPohgWrY5JGd/8WJDkZc=,tag:KE68f8xLNQX75SnRckInKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTXVhS2ZpNjFWUDQxaUFl
            VGpHdFluSHhsYkdoTXAzVFpZRHFyQzBXMkFzClo5YXJOYWFLT1FUU2Q4Z0xSb3Rt
            V1ZmU0MvUFdVNWNQZThSbDhOWlptRncKLS0tIDM1ellZOEVEaitiajhDem03SFc0
            WmlIL1NpTVVPa0t2S2hLd0JrbkJDcU0Ki8tGfFX8qiFWvmt9Sxl9bAjrFqCpjX1W
            gi4GnsvFNUwjDNe1sjA6Qxj8Ln5WIwCBb7MdOcbjuGwQs4hK/E+Mvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qplnvx547350cey8e87jq9mp2nex64evcd3n2sclsuq8xdllddssrjrs8k
    lastmodified: "2026-07-20T12:18:45Z"
    mac: ENC[AES256_GCM,data:aBIlLYFDPUJXuAdZ7F8DEaD/BscDas8DZ8eF+BjjGuJ18+AjI06u1RDcsx7ZerL3d68UE3XS+dLSUW8tnnFxhbBRzClKq+RhBb1I7S2c+qaaVTJkAJ+Y0IsgjwEhIl5pTZo4JI7MjjopOcIX8LktaQXLPdBCsTai2Lhh5SWLypg=,iv:pju9gHPoW8nQ83Wk6laHsApcPKyYhsFIvHYfgiDjrsA=,tag:oNxZCyTolfWLmU1jxcGBgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
