apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      containers:
        - name: backend-api
          image: ${IMAGE}
          resources:
            requests:
              cpu: "60m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "120Mi"

          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            timeoutSeconds: 3  
            failureThreshold: 12    # 12 × 5 сек = 1 минута на старт
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            timeoutSeconds: 3  
            initialDelaySeconds: 0
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            timeoutSeconds: 3  
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3


---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: default
  labels:
    app: backend-api
spec:
  selector:
    
    app: backend-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP