secret:
    dbName: ENC[AES256_GCM,data:ZkovmOs=,iv:sMCthyc+j7jlMeKnty0CGswWFLNX/8rTE82thtr550o=,tag:KD5XcI6lMNMDGt/p10cIvQ==,type:str]
    dbUser: ENC[AES256_GCM,data:CChS1fsbt4K0Iw==,iv:jw73NqPkBLdS7RJZ+Dij0IFGTzUtaRrHzKGB1nzvJP8=,tag:sYXlSZHhSNyIrxFGU7jKYw==,type:str]
    dbPassword: ENC[AES256_GCM,data:T3bxNsHyB3Q86i4BMf6NazU3R48E,iv:xJii7M2nxWjY9E5Tw9tBCF80ZOTcTy3JNsd6907oMP0=,tag:75flPJ51qpRF+znQy+FEcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR2hOMnlVb05FbnowZXZN
            bWRtOGVtT1JGbGdLL3FHTjJtWHdRaXdZQzNjCnpaQTBOOFNvOTBjMlNUREl0TDls
            RWhYalluV2hoYjBjUFRqa2pCV3A3bTQKLS0tIFgwYVlSVFRDVFFFNlkzMjBXWUVh
            NngxOHRyQkNLVFdaZEdxWDVUbmxsNlEKqmuFGJk/a1N/MSIcRxMlctFvBopIxJ2C
            K7tYEz0++a/2mEu5wKkIdjbMXmaOaX/c5e0dHt3XuYhqrWfXTM5o2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qplnvx547350cey8e87jq9mp2nex64evcd3n2sclsuq8xdllddssrjrs8k
    lastmodified: "2026-07-20T12:18:47Z"
    mac: ENC[AES256_GCM,data:3WvYwSP93SGF0+T6YiH5nlt7nZfiZIELCh46G6HBbBTOoIu0gGcffQzZeL5k26ZslPOw19tGgcAYwCw9sUysx+hc+NrGF6lZAZEdzBo42hOQ5up45kQewBZCrUdyW1Fdf4NeYsA/n24Oaso8GNOHNiOg7TNxeJ/hmcOm/AZYFeA=,iv:jDz1CJTL2zeRVXcpTNev1K+221gF9hMbIj/kWmh86Js=,tag:CnbgmcWQJWqdpFlSNGRvZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
