name: Build and Push

on:
  workflow_call:
    outputs:
      image_sha:
        description: "Docker image tag with commit sha"
        value: ${{ jobs.build-push.outputs.image_sha }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.build-push.outputs.image_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ vars.DOCKER_USER }} --password-stdin

      - name: Build and push image to Docker Hub
        id: build-push
        env:
          IMAGE_SHA: ${{ vars.DOCKER_USER }}/backend:sha-${{ github.sha }}
          IMAGE_LATEST: ${{ vars.DOCKER_USER }}/backend:latest
        run: |
          docker build -t $IMAGE_SHA -t $IMAGE_LATEST .
          docker push $IMAGE_SHA
          docker push $IMAGE_LATEST
          echo "image_sha=$IMAGE_SHA" >> $GITHUB_OUTPUT
