name: Deploy k8s

on:
  push:
    branches: [main]

jobs:
  checks:
    uses: ./.github/workflows/pr-check.yml

  build:
    needs: [checks]
    uses: ./.github/workflows/build-push.yml
    secrets: inherit

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy-argocd.yml
    with:
      helm_path: helmCharts/backend-api/values-production.yaml
      image_name: ${{ needs.build.outputs.image_sha }}
      branch: main
      gitops_repo: BurakMikita/argocd-devops
      argocd_app_name: backend-api
      argocd_server: ${{ vars.ARGOCD_SERVER }}
    secrets:
      gitops_token: ${{ secrets.GITOPS_TOKEN }}
      argocd_auth_token: ${{ secrets.ARGOCD_AUTH_TOKEN }}

  notify:
    name: Notify JOBs
    needs: [checks, deploy, build]
    if: always()
    uses: ./.github/workflows/notify.yml
    with:
      check_result: ${{ needs.checks.result }}
      deploy_result: ${{ needs.deploy.result }}
    secrets: inherit
