name: DEPLOY

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    uses: ./.github/workflows/pr-check.yml

  deploy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         passphrase: ${{ secrets.SSH_PASSPHRASE }}
         script: |
           cd /var/www/myapp/backend
           git pull origin main
           cd /var/www/my-app
           docker-compose up -d --build backend


      
      