name: DEPLOY

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    uses: ./.github/workflows/pr-check.yml

  deploy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         passphrase: ${{ secrets.SSH_PASSPHRASE }}
         script: |
           if [ -d ~/backend ]; then
             cd ~/backend && git pull origin main
           else
             git clone https://github.com/it-incubator/devops-backend ~/backend
           fi
           mkdir -p ~/myapp2
           cat > ~/myapp2/docker-compose.yml << 'EOF'
           services:
             back:
               build: /root/backend
               ports: ["3001:3000"]
           EOF
           cd ~/myapp2
           docker compose up -d --build


      
      