name: DEPLOY

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    uses: ./.github/workflows/pr-check.yml

  deploy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         passphrase: ${{ secrets.SSH_PASSPHRASE }}
         script: |
           if [ -d "/var/www/myapp/backend" ]; then
             cd /var/www/myapp/backend && git pull origin main
           else
             mkdir -p /var/www/myapp
             git clone https://github.com/it-incubator/devops-backend /var/www/myapp/backend
           fi
           cd ~/myapp2
           docker compose up -d --build


      
      