apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: talaka-postgres
spec:
  serviceName: talaka-postgres
  replicas: 1
  selector:
    matchLabels:
      app: talaka-postgres
  template:
    metadata:
      labels:
        app: talaka-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: talaka-backend-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: talaka-backend-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: talaka-config
                  key: DB_NAME
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: talaka-postgres
spec:
  selector:
    app: talaka-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
